# Generated by Django 4.2.17 on 2024-12-15 17:22

from django.db import migrations

def seed_categorias(apps, schema_editor):
    Categoria = apps.get_model('articulos', 'Categoria')
    categorias_iniciales = [
        'Tecnología', 'Ciencia', 'Deportes', 'Arte', 'Música', 
        'Política', 'Economía', 'Cultura', 'Sociales', 'Farándula', 'Policial'
    ]
    for nombre in categorias_iniciales:
        try:
            Categoria.objects.get_or_create(nombre=nombre)
        except Exception as e:
            print(f"Error al crear la categoría {nombre}: {e}")
#clases
class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        # Seeder para insertar las categorías iniciales
        migrations.RunPython(seed_categorias),
    ]
