# Generated by Django 4.2.17 on 2024-12-16 03:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_categoria_articulo_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='articulos.categoria'),
            preserve_default=False,
        ),
    ]
