# Generated by Django 4.2.17 on 2024-12-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_categoria_articulo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
