# Generated by Django 4.2.17 on 2024-12-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_articulo_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
    ]
